default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: dirlic
  password: 123456

  
development:
  <<: *default
  database: ecs_development


test:
  <<: *default
  database: ecs_test


production:
  <<: *default
  database: ecs_production
  username: dirlic
  password: <%= ENV['IACHEI_APP_DATABASE_PASSWORD'] %>
