default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  
development:
  <<: *default
  database: ecs_development


test:
  <<: *default
  database: ecs_test


production:
  <<: *default
  username: dirlic
  password: <%= ENV['ECS_PRODUCTION_DATABASE_PASSWORD'] %>
